# ArgoCD PostSync hook: create TargetGroupBinding from ConfigMap default/bootstrap-output (api_target_group_arn).
apiVersion: batch/v1
kind: Job
metadata:
  name: post-sync-create-targetgroupbinding
  namespace: rosa-regional-frontend
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: post-sync-patch-tgb
      restartPolicy: OnFailure
      containers:
        - name: create
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              set -e
              ARN=$(kubectl get configmap bootstrap-output -n default -o jsonpath='{.data.api_target_group_arn}')
              if [ -z "$ARN" ]; then
                echo "bootstrap-output api_target_group_arn is empty, skipping TargetGroupBinding create"
                exit 0
              fi
              kubectl apply -f - <<EOF
              apiVersion: eks.amazonaws.com/v1
              kind: TargetGroupBinding
              metadata:
                name: rosa-regional-frontend
                namespace: rosa-regional-frontend
              spec:
                serviceRef:
                  name: rosa-regional-frontend
                  port: 8080
                targetGroupARN: "$ARN"
                targetType: ip
              EOF
              echo "Created/updated TargetGroupBinding with ARN from default/bootstrap-output"